name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9]
        plone: ["6.0-latest", "5.2-latest"]
        exclude:
          - plone: "5.2-latest"
            python: 3.9
          - plone: "6.0-latest"
            python: 3.8

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Plone ${{ matrix.plone }}
        run: |
          pip install -U pip setuptools wheel -c https://dist.plone.org/release/${{ matrix.plone }}/constraints.txt
          pip install Plone plone.app.testing -c https://dist.plone.org/release/${{ matrix.plone }}/constraints.txt

      - name: Install
        run: |
          pip install -e ".[test]"

      - name: test
        run: |
          zope-testrunner --auto-color --auto-progress --test-path .
